name: Lint & Test

on:
  pull_request: {}
  workflow_call: {}

jobs:
  lint:
    name: Lint & Formatting Check
    uses: ./.github/workflows/lint.yml

  test:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    needs: lint
